# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 256751bf4544cb5ab82349ccf2f055b0dc90eff177612b93df299a4d56e26c00c367717854b8de519acf60e23651ebd75dbdf242f510963d00e3f257f6529746

test:
  secret_key_base: 9fdabb99aeb5fb2d6ad507f3265cf83c29299188b060c0924e937949395b4567d60afb5625e8f49a7c7b759c49cac0ebe847649bb949c5b55ff503aaad68f1c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
